"""Initial migration

Revision ID: feaeeee9389e
Revises: 
Create Date: 2026-07-21 20:35:30.714548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feaeeee9389e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('totp_enabled', sa.Boolean(), nullable=True))
        batch_op.drop_column('mfa_expiry')
        batch_op.drop_column('mfa_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mfa_code', sa.VARCHAR(length=6), nullable=True))
        batch_op.add_column(sa.Column('mfa_expiry', sa.DATETIME(), nullable=True))
        batch_op.drop_column('totp_enabled')
        batch_op.drop_column('totp_secret')

    # ### end Alembic commands ###
